language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
before_script:
- npm install
script:
- npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token:
    secure: "crELopNQ8SUwIQDpFxMxAuAxlY0Qr4344sEDST1x6qnVQaxfCwKbdsadXs65kr19+bjRVzmIlHVUvShbVPFjOsJf0SVwUAIZSP32b4TvUgEMx/p7ibE+J7pJpdXSjy4TQDx5zhh3anLjAq2Gx2nv6+gKxmsMXwRdVds00V/oDSMDkzM5f+zVseCq0pGACuWzLEorW3vneXgsHvEJJ4jJfKwWUPJyX0pAfXpR8BIl+Udi359R+CtSD9maD5Yi43FEwu6tCUoeAJaQGpcq6KkHbns9b3kpQrXp+Btck6PbsrisRR5vSceY6Y7TAjSXM8Y5nTu0i1/LDsaOMQ0p8Qk1em3QPOrO6nq3Yjfob9FAzohvGRr1y8CJYVXVsBjLMS6tagNFz8UQxbv4xQslA5yLp8q/+sPWbMy77AmQChaCqW4OjmD5auh+CkMp+NlnS8hPnCJoSh7BODPpTjPrHYYx+zIp5fDTkg7Y3OXliZ97EIHK4aep2aqbM+Du4kC5j4JUgh9vTbAxYv/5bQaX08Tcs+A0/k4TbYg1Uw6g9F53vnXqt4YpBxIqMfy8lqxvgn62OEM41AJduK7oWmf6SAqAwFdSE0z4lOmAe4eogGCYaiS/iGR5b8r32tHTyzbMg0vSuKKvJs00SqYOtXHM6+fuK5VHgLDirCxtAVsVSGl2ctk="
  keep_history: true
  on:
    branch: master
