language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
before_script:
- npm install
script:
- npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token:
    secure: rUYB33YYFBVF5XKZEfYZhY8pBj/V63AtrrlgRVfacjXrxB7lmOZPaX0AbOlYlzFla/L6FfuAPv+J7E9f0ePHvl10lSIiE5HeHYbCDUI/NEH4zhBy4Op88nQm/ycOqgGm9JH0EfsYmiKVYR0NEBmRcQrourlGqVopWBgu0lIrbSgf2ZjNEnlbImOnxxaQEyD4pWHz6nAq1Uv2xhKFyCHGuWice1/fALYbRPI2gkwWdfDZANA6mGXhDuE0VTj0Xd06qBqM9PRTV1l38B6shc3DOs48q9txmJeReH0y5IY9vqMjXzBPURNLZIaC287dXh53YbaLFafBtYmx8EimIWLgF8+QzHXJ+/Q04qXIeKyy+8TzeAhuEHkr7mXwOk/A34Lloffljmcx6BgEgCdlxeisife438g8jrMpnaM4K+FecOj0ma00pKXkLlvRCxAVHIGH8+ow1IqSlmmq0XvLqWJHMFER1v23Nxmua3kNK0svvkL9SfTO9eR52BV3redJWhws2xIy5TEYyuJBX2bg7dQCM1/38eTqFcGBqzXuKD9F30S+CkD75ane6N968edhjeCQwXGFGaUETOh4R4vzISjZIo+IAbPtmnPv1M5So2snnBXLxs6m4hJsgoKG7GThEiSWE4yfzd3Qy/Ip4iyWPKkTd3IaXzpv96gkHEJOCt3q74g=
  keep_history: true
  on:
    branch: master
env:
  global:
    secure: rUYB33YYFBVF5XKZEfYZhY8pBj/V63AtrrlgRVfacjXrxB7lmOZPaX0AbOlYlzFla/L6FfuAPv+J7E9f0ePHvl10lSIiE5HeHYbCDUI/NEH4zhBy4Op88nQm/ycOqgGm9JH0EfsYmiKVYR0NEBmRcQrourlGqVopWBgu0lIrbSgf2ZjNEnlbImOnxxaQEyD4pWHz6nAq1Uv2xhKFyCHGuWice1/fALYbRPI2gkwWdfDZANA6mGXhDuE0VTj0Xd06qBqM9PRTV1l38B6shc3DOs48q9txmJeReH0y5IY9vqMjXzBPURNLZIaC287dXh53YbaLFafBtYmx8EimIWLgF8+QzHXJ+/Q04qXIeKyy+8TzeAhuEHkr7mXwOk/A34Lloffljmcx6BgEgCdlxeisife438g8jrMpnaM4K+FecOj0ma00pKXkLlvRCxAVHIGH8+ow1IqSlmmq0XvLqWJHMFER1v23Nxmua3kNK0svvkL9SfTO9eR52BV3redJWhws2xIy5TEYyuJBX2bg7dQCM1/38eTqFcGBqzXuKD9F30S+CkD75ane6N968edhjeCQwXGFGaUETOh4R4vzISjZIo+IAbPtmnPv1M5So2snnBXLxs6m4hJsgoKG7GThEiSWE4yfzd3Qy/Ip4iyWPKkTd3IaXzpv96gkHEJOCt3q74g=
